# Generated by Django 5.1.4 on 2025-01-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
