# Generated by Django 5.1.4 on 2025-01-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordrow',
            options={},
        ),
        migrations.AddField(
            model_name='recordrow',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to='todo.recordrow')),
            ],
        ),
    ]
