# Generated by Django 5.1.4 on 2025-02-08 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_assignedtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedTask',
        ),
    ]
