# Generated by Django 5.1.4 on 2025-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
