# Generated by Django 5.1.4 on 2025-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teammember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='role',
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
