# Generated by Django 5.1.4 on 2025-02-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigntask', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedtask',
            old_name='task_name',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='assignedtask',
            old_name='user_name',
            new_name='user',
        ),
    ]
